require_relative 'piece'
require_relative 'sliding_piece'
require_relative 'stepping_piece'
require_relative 'rook'
require_relative 'queen'
require_relative 'knight'
require_relative 'king'
require_relative 'bishop'
